<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\mk8.email.Configuration\mk8.email.Configuration.csproj" />
    <ProjectReference Include="..\mk8.email.Contracts\mk8.email.Contracts.csproj" />
    <ProjectReference Include="..\mk8.email.Hosting\mk8.email.Hosting.csproj" />
    <ProjectReference Include="..\mk8.email.Messaging\mk8.email.Messaging.csproj" />
  </ItemGroup>

</Project>
