<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\mk8.email.Application\mk8.email.Application.Core.csproj" />
    <ProjectReference Include="..\mk8.email.Configuration\mk8.email.Configuration.csproj" />
    <ProjectReference Include="..\mk8.email.Contracts\mk8.email.Contracts.csproj" />
    <ProjectReference Include="..\mk8.email.Infrastructure\mk8.email.Infrastructure.csproj" />
  </ItemGroup>

</Project>
