<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DnsClient" Version="1.8.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.4" />
    <PackageReference Include="Meziantou.Analyzer" Version="3.0.270" PrivateAssets="all" />
    <PackageReference Include="Roslynator.Analyzers" Version="5.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" PrivateAssets="all" />
    <PackageReference Include="NetFabric.Hyperlinq.Analyzer" Version="2.3.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="BannedSymbols.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\mk8.email.Configuration\mk8.email.Configuration.csproj" />
    <ProjectReference Include="..\mk8.email.Contracts\mk8.email.Contracts.csproj" />
    <ProjectReference Include="..\mk8.email.MailWire\mk8.email.MailWire.csproj" />
    <ProjectReference Include="..\mk8.email.Messaging\mk8.email.Messaging.csproj" />
  </ItemGroup>

</Project>
