namespace mk8.email.Contracts.Messaging;

// Stable domain identifiers, not protocol method names. Failure is result-only;
// None represents an unsupported request or unmatched dependency prepared by Gateway.
public enum MailOperationKind
{
    None = 0,
    Failure = 1,
    Echo = 2,
    ReadFolders = 10,
    FindFolders = 11,
    ReadFolderChanges = 12,
    FindFolderChanges = 13,
    MutateFolders = 14,
    ReadThreads = 20,
    ReadThreadChanges = 21,
    ReadMessages = 30,
    FindMessages = 31,
    ReadMessageChanges = 32,
    FindMessageChanges = 33,
    MutateMessages = 34,
    ImportMessages = 35,
    CopyMessages = 36,
    ParseMessages = 37,
    ReadSearchSnippets = 38,
    ReadMessageContent = 39,
    ReadSenderIdentities = 40,
    ReadSenderIdentityChanges = 41,
    MutateSenderIdentities = 42,
    ReadSubmissions = 50,
    FindSubmissions = 51,
    ReadSubmissionChanges = 52,
    FindSubmissionChanges = 53,
    MutateSubmissions = 54,
    ReadVacationSettings = 60,
    MutateVacationSettings = 61,
    ReadNotificationSubscriptions = 70,
    MutateNotificationSubscriptions = 71,
    CopyBinaryObjects = 80,
    ReadAddressBooks = 90,
    ReadAddressBookChanges = 91,
    MutateAddressBooks = 92,
    ReadContacts = 100,
    FindContacts = 101,
    ReadContactChanges = 102,
    FindContactChanges = 103,
    MutateContacts = 104,
    CopyContacts = 105,
}
