<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\mk8.email.Configuration\mk8.email.Configuration.csproj" />
    <ProjectReference Include="..\mk8.email.Contracts\mk8.email.Contracts.csproj" />
    <ProjectReference Include="..\mk8.email.MailWire\mk8.email.MailWire.csproj" />
    <ProjectReference Include="..\mk8.email.Messaging\mk8.email.Messaging.csproj" />
  </ItemGroup>

</Project>
